My_Blog_Project/App_Blog/urls.py
from django.urls import path
from . import views

app_name='App_Blog'

urlpatterns=[
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug>/',views.blog_details,name='blog_details'),
    path('like/<pk>/',views.liked,name='liked_post'),
    path('unlike/<pk>/',views.unliked,name='unlike_post'),
    path('my-blogs/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
]

My_Blog_Project/App_Login/urls.py
from django.urls import path
from . import views

app_name='App_Login'

urlpatterns=[
 path('signup/', views.sign_up, name='signup'),
 path('login/', views.login_page, name='login'),
 path('logout/', views.logout_user, name='logout'),
 path('profile/',views.profile, name='profile'),
 path('change-profile/',views.user_change,name='change-profile'),
 path('password/',views.pass_change,name='password'),
 path('add-picture/',views.add_pro_pic, name='add-picture'),
 path('change-picture/',views.change_pro_pic, name='change-picture')


]

My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Blog_Project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/80105808da.js" crossorigin="anonymous"></script>


<title>{% block title_block %} Blogs {% endblock %}</title>
  </head>
   <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item-active">
          <a class="nav-link" href="{% url 'index' %}"><img src="/media/logo.png" width="50px" alt=""></a>

        </li>

        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop"  data-bs-toggle="dropdown" role="button">
            @{{user.username}}
          </a>
          <div class="dropdown-menu">
           <a class="dropdown-item" href="{% url 'App_Blog:create_blog'%}">Write Blog</a>
           <a class="dropdown-item" href="{% url 'App_Blog:my_blogs'%}">My Blog</a>
           <a class="dropdown-item" href="{% url 'App_Login:profile'%}">Profile</a>
           <hr>
           <a class="dropdown-item" href="{% url 'App_Login:logout'%}">Log out</a>
         </div>
        </div>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up </a>
        </li>
        <li class="nav-item">
          <a class=" nav-link" href="{% url 'App_Login:login'%}">Log In</a>
        </li>
        {% endif %}

      </ul>
    </nav>

    <div class="container" style="padding-top:20px">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>